# Listar todas as empresas
GET http://localhost:8080/empresas

# Criar uma nova empresa
POST http://localhost:8080/empresas
Content-Type: application/json

{
  "id": 6,
  "nome": "Zeta Tech Mackenzie",
  "cnpj": "44.555.666/0001-77",
  "emailContato": "tech@zeta.com"
}

# Atualizar uma empresa existente
PUT http://localhost:8080/empresas/1
Content-Type: application/json

{
  "nome": "Empresa Alfa LTDA Atualizada",
  "cnpj": "12.345.678/0001-90",
  "emailContato": "novo-contato@alfa.com"
}

# Deletar uma empresa
DELETE http://localhost:8080/empresas/5

# Listar todos os estudantes
GET http://localhost:8080/estudantes

# Criar um novo estudante
POST http://localhost:8080/estudantes
Content-Type: application/json

{
  "id": 11,
  "nome": "Rique Estudante",
  "email": "rique@mackenzie.br",
  "nascimento": "2000-01-01",
  "anoIngresso": 2024
}

# Deletar um estudante
DELETE http://localhost:8080/estudantes/10

# Listar todas as vagas
GET http://localhost:8080/vagas

# Criar uma nova vaga
POST http://localhost:8080/vagas
Content-Type: application/json

{
  "id": 8,
  "titulo": "Estagiário de TI",
  "descricao": "Vaga para suporte e desenvolvimento inicial",
  "publicacao": "2026-04-12",
  "ativo": true,
  "idEmpresa": 1
}